import { RefillCase, User, AuditLogItem, IntegrationServiceItem, NotificationItem, KnowledgeDoc } from '../types';

export const DEMO_USERS: User[] = [
  {
    id: "usr-pharm-01",
    email: "pharmacy@rxresolve.demo",
    name: "Elena Rostova, CPhT",
    role: "PHARMACY_STAFF",
    role_title: "Lead Pharmacy Technician",
    organization_id: "org-pharm-01",
    organization_name: "Downtown Pharmacy",
    organization_type: "PHARMACY",
    avatar: "https://images.unsplash.com/photo-1594824813583-30f14652c206?w=150"
  },
  {
    id: "usr-pract-01",
    email: "practice@rxresolve.demo",
    name: "Maya Lin, BSN",
    role: "PRACTICE_STAFF",
    role_title: "Practice Care Coordinator",
    organization_id: "org-pract-01",
    organization_name: "Downtown Physician Group",
    organization_type: "PRACTICE",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150"
  },
  {
    id: "usr-prov-01",
    email: "provider@rxresolve.demo",
    name: "Dr. Sarah Wilson, MD",
    role: "PROVIDER",
    role_title: "Attending Physician, Internal Medicine",
    organization_id: "org-pract-01",
    organization_name: "Downtown Physician Group",
    organization_type: "PRACTICE",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150"
  },
  {
    id: "usr-admin-01",
    email: "admin@rxresolve.demo",
    name: "Marcus Vance",
    role: "ADMIN",
    role_title: "Director of Clinical Operations",
    organization_id: "org-healthsys-01",
    organization_name: "Metropolitan Health System",
    organization_type: "HEALTH_SYSTEM",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150"
  }
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();

export const INITIAL_CASES: RefillCase[] = [
  {
    id: "RX-10482",
    patient_id: "pat-10482",
    patient_name: "Alex Johnson",
    patient_dob: "1988-04-14",
    patient_phone: "555-014-8821",
    medication_id: "med-01",
    medication_name: "Demo Medication 10mg",
    dosage: "10mg PO Daily",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    last_fill_date: "2026-07-12",
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    pharmacy_phone: "555-321-9988",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "WAITING_FOR_PROVIDER",
    previous_status: "INVESTIGATING",
    last_status_reason: "No refills remaining; provider authorization required",
    blocker: "No refills remaining",
    blocker_category: "Provider-related",
    priority: "HIGH",
    priority_score: 78,
    owner_id: "usr-prov-01",
    owner_name: "Dr. Sarah Wilson",
    owner_role: "PROVIDER",
    required_next_action: "Provider review required",
    sla_deadline: hoursFromNow(18),
    sla_hours_remaining: 18.0,
    sla_status: "HEALTHY",
    information_completeness: {
      patient_info: true,
      medication_info: true,
      pharmacy_info: true,
      prescription_details: true,
      provider_info: true,
      required_review_completed: false,
      details: {
        patient: "Alex Johnson (DOB: 1988-04-14) - Chart Active",
        medication: "Demo Medication 10mg (NDC: 43598-012-30)",
        pharmacy: "Downtown Pharmacy (NPI: 1942857102)",
        provider: "Dr. Sarah Wilson (NPI: 1092837411)"
      }
    },
    ai_analysis: {
      blocker: "Provider authorization",
      category: "Provider-related",
      confidence: 0.94,
      recommended_action: "Route to physician practice for provider review.",
      recommended_role: "PROVIDER",
      operational_priority: "High",
      reasoning: "Existing prescription has no refills remaining. Provider clinical sign-off is required under SOP §4.2.",
      summary: "Refill request received from Downtown Pharmacy. Existing prescription has no refills remaining. Provider authorization is required. Patient and pharmacy information are complete. Case is currently waiting for provider review.",
      rag_sources: [
        {
          source: "Practice Refill SOP §4.2",
          title: "Provider Authorization & Refill Sign-Off Policy",
          category: "Practice SOPs",
          snippet: "When an existing prescription has zero (0) refills remaining, standard protocol dictates that an explicit provider authorization is required. Practice staff may not re-authorize refills independently without provider review."
        }
      ],
      created_at: hoursAgo(2)
    },
    notes: "Patient Alex Johnson taking Demo Medication 10mg maintenance. Refills exhausted.",
    created_at: hoursAgo(6),
    updated_at: hoursAgo(1)
  },
  {
    id: "RX-10483",
    patient_id: "pat-10483",
    patient_name: "Marcus Thorne",
    patient_dob: "1975-11-20",
    medication_id: "med-02",
    medication_name: "Atorvastatin 40mg",
    dosage: "40mg PO QPM",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "WAITING_FOR_PROVIDER",
    blocker: "No refills remaining",
    blocker_category: "Provider-related",
    priority: "MEDIUM",
    priority_score: 55,
    required_next_action: "Provider review required",
    sla_hours_remaining: 14.5,
    sla_status: "HEALTHY",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(9),
    updated_at: hoursAgo(2)
  },
  {
    id: "RX-10484",
    patient_id: "pat-10484",
    patient_name: "Eleanor Vance",
    patient_dob: "1962-03-09",
    medication_id: "med-03",
    medication_name: "Ozempic 1mg/dose Pen",
    dosage: "1mg SQ Weekly",
    quantity: 1,
    days_supply: 28,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-02",
    pharmacy_name: "MetroCare Community Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "WAITING_FOR_INSURANCE",
    blocker: "Prior authorization required",
    blocker_category: "Insurance/administrative",
    priority: "HIGH",
    priority_score: 75,
    required_next_action: "Submit ePA criteria to payer",
    sla_hours_remaining: 6.2,
    sla_status: "WARNING",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(18),
    updated_at: hoursAgo(4)
  },
  {
    id: "RX-10485",
    patient_id: "pat-10485",
    patient_name: "Carlos Mendez",
    patient_dob: "1994-08-30",
    medication_id: "med-04",
    medication_name: "Amoxicillin 875mg",
    dosage: "875mg PO BID x 10d",
    quantity: 20,
    days_supply: 10,
    refills_requested: 1,
    refills_remaining: 1,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "WAITING_FOR_PHARMACY",
    blocker: "Quantity clarification",
    blocker_category: "Pharmacy-related",
    priority: "MEDIUM",
    priority_score: 45,
    required_next_action: "Awaiting pharmacy response on dispensed packaging",
    sla_hours_remaining: 21.0,
    sla_status: "HEALTHY",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(3),
    updated_at: hoursAgo(1)
  },
  {
    id: "RX-10487",
    patient_id: "pat-10487",
    patient_name: "David Kim",
    patient_dob: "1983-05-18",
    medication_id: "med-05",
    medication_name: "Sertraline 50mg",
    dosage: "50mg PO Daily",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "ACTION_REQUIRED",
    blocker: "Provider authorization required",
    blocker_category: "Provider-related",
    priority: "HIGH",
    priority_score: 85,
    required_next_action: "Provider approved; dispatch electronic script",
    sla_hours_remaining: 2.5,
    sla_status: "WARNING",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: true },
    created_at: hoursAgo(22),
    updated_at: hoursAgo(2)
  },
  {
    id: "RX-10490",
    patient_id: "pat-10490",
    patient_name: "Sophia Al-Mansoor",
    patient_dob: "1995-07-11",
    medication_id: "med-06",
    medication_name: "Vyvanse 30mg",
    dosage: "30mg PO QAM",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "ESCALATED",
    blocker: "Patient visit may be required",
    blocker_category: "Provider-related",
    priority: "CRITICAL",
    priority_score: 92,
    required_next_action: "Controlled substance protocol: Schedule clinic encounter",
    sla_hours_remaining: 1.0,
    sla_status: "BREACHED",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(23),
    updated_at: hoursAgo(1)
  },
  {
    id: "RX-10491",
    patient_id: "pat-10491",
    patient_name: "Liam O'Connor",
    patient_dob: "1972-04-03",
    medication_id: "med-07",
    medication_name: "Amlodipine 5mg",
    dosage: "5mg PO Daily",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "FAILED",
    blocker: "EHR unavailable",
    blocker_category: "System/integration",
    priority: "CRITICAL",
    priority_score: 95,
    required_next_action: "EHR FHIR gateway timed out; retrying safely",
    sla_hours_remaining: 0.5,
    sla_status: "BREACHED",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(24),
    updated_at: hoursAgo(1)
  },
  {
    id: "RX-10492",
    patient_id: "pat-10492",
    patient_name: "Jordan Taylor",
    patient_dob: "1982-08-14",
    patient_phone: "555-018-4921",
    medication_id: "med-08",
    medication_name: "Lisinopril 10mg",
    dosage: "10mg PO Daily",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    pharmacy_phone: "555-321-9988",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "NEW",
    previous_status: "NEW",
    last_status_reason: "Initial refill request intake via Surescripts",
    blocker: "No refills remaining",
    blocker_category: "Provider-related",
    priority: "LOW",
    priority_score: 28,
    owner_id: "usr-pract-01",
    owner_name: "Maya Lin, BSN",
    owner_role: "PRACTICE_STAFF",
    required_next_action: "Initial intake verification & chart review",
    sla_deadline: hoursFromNow(24),
    sla_hours_remaining: 24.0,
    sla_status: "HEALTHY",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    ai_analysis: {
      blocker: "No refills remaining",
      category: "Provider-related",
      confidence: 0.95,
      recommended_action: "Conduct intake triage and forward to provider for routine chronic renewal.",
      recommended_role: "PRACTICE_STAFF",
      operational_priority: "Low",
      reasoning: "Routine chronic therapy with compliant fill history. Low clinical risk; ready for standard practice triage.",
      summary: "New refill intake received for Lisinopril 10mg. Patient has 0 refills remaining.",
      created_at: hoursAgo(1)
    },
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1)
  },
  {
    id: "RX-10493",
    patient_id: "pat-10493",
    patient_name: "Hannah Abbott",
    patient_dob: "1991-02-17",
    patient_phone: "555-012-9932",
    medication_id: "med-09",
    medication_name: "Omeprazole 20mg",
    dosage: "20mg PO Daily",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "TRIAGING",
    blocker: "Missing patient information",
    blocker_category: "Information-related",
    priority: "LOW",
    priority_score: 30,
    owner_id: "usr-pract-01",
    owner_name: "Maya Lin, BSN",
    owner_role: "PRACTICE_STAFF",
    required_next_action: "Contact patient for secondary insurance member ID",
    sla_deadline: hoursFromNow(22),
    sla_hours_remaining: 22.0,
    sla_status: "HEALTHY",
    information_completeness: { patient_info: false, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(2),
    updated_at: hoursAgo(1)
  }
];

export const DEMO_ANALYTICS = {
  kpis: {
    total_refills: 142,
    active_refills: 16,
    avg_resolution_hours: 4.2,
    sla_compliance_rate: 94.7,
    ai_acceptance_rate: 91.2,
    awaiting_provider: 4,
    missing_information: 2,
    at_risk: 2,
    resolved_today: 4
  },
  bottlenecks: [
    { name: "Provider-related", count: 8, percentage: 50.0 },
    { name: "Insurance/administrative", count: 3, percentage: 18.8 },
    { name: "Pharmacy-related", count: 2, percentage: 12.5 },
    { name: "Information-related", count: 2, percentage: 12.5 },
    { name: "System/integration", count: 1, percentage: 6.2 }
  ],
  volume_trend: [
    { day: "Mon", submitted: 24, resolved: 22 },
    { day: "Tue", submitted: 31, resolved: 29 },
    { day: "Wed", submitted: 28, resolved: 26 },
    { day: "Thu", submitted: 35, resolved: 32 },
    { day: "Fri", submitted: 29, resolved: 28 },
    { day: "Sat", submitted: 12, resolved: 11 },
    { day: "Sun", submitted: 8, resolved: 8 }
  ],
  resolution_buckets: [
    { bucket: "< 2 hrs", count: 28, label: "Instant / Fast Path" },
    { bucket: "2-6 hrs", count: 45, label: "Provider Same-Day" },
    { bucket: "6-12 hrs", count: 31, label: "Standard Review" },
    { bucket: "12-24 hrs", count: 18, label: "Information Retrieval" },
    { bucket: "> 24 hrs", count: 6, label: "Complex / Prior Auth" }
  ],
  organizations: [
    {
      org_name: "Downtown Physician Group",
      type: "PRACTICE",
      active_cases: 14,
      resolved_this_month: 482,
      avg_resolution_hours: 6.8,
      sla_compliance_pct: 94.2
    },
    {
      org_name: "Downtown Pharmacy",
      type: "PHARMACY",
      active_cases: 9,
      resolved_this_month: 614,
      avg_resolution_hours: 5.4,
      sla_compliance_pct: 96.1
    },
    {
      org_name: "Metropolitan Health System",
      type: "HEALTH_SYSTEM",
      active_cases: 23,
      resolved_this_month: 1096,
      avg_resolution_hours: 7.2,
      sla_compliance_pct: 95.8
    },
    {
      org_name: "MetroCare Community Pharmacy",
      type: "PHARMACY",
      active_cases: 5,
      resolved_this_month: 320,
      avg_resolution_hours: 4.8,
      sla_compliance_pct: 97.4
    }
  ],
  commercial_roi: {
    disclaimer: "DEMO / SIMULATED BENCHMARKS",
    annual_hours_saved: 2450,
    cost_avoidance_annual: 85750,
    therapy_abandonment_reduction_pct: 34.2
  }
};

export const DEMO_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "aud-01",
    timestamp: hoursAgo(6),
    case_id: "RX-10482",
    actor_type: "HUMAN",
    actor_id: "usr-pharm-01",
    actor_name: "Elena Rostova, CPhT",
    actor_role: "PHARMACY_STAFF",
    action: "CREATE_REFILL_CASE",
    event_type: "CASE_CREATION",
    previous_state: null as any,
    new_state: "NEW",
    confidence: 1.0,
    details: { source: "Surescripts NCPDP", patient: "Alex Johnson", medication: "Demo Medication 10mg" }
  },
  {
    id: "aud-02",
    timestamp: hoursAgo(5.8),
    case_id: "RX-10482",
    actor_type: "AI",
    actor_id: "rxresolve-ai",
    actor_name: "RxResolve AI",
    actor_role: "SYSTEM",
    action: "BLOCKER_CLASSIFIED",
    event_type: "AI_INFERENCE",
    previous_state: "NEW",
    new_state: "TRIAGING",
    confidence: 0.94,
    details: { primary_blocker: "No refills remaining", category: "Provider-related", sop_applied: "Practice SOP §4.2" }
  },
  {
    id: "aud-03",
    timestamp: hoursAgo(4.5),
    case_id: "RX-10482",
    actor_type: "HUMAN",
    actor_id: "usr-pract-01",
    actor_name: "Maya Lin, BSN",
    actor_role: "PRACTICE_STAFF",
    action: "ROUTE_TO_PROVIDER",
    event_type: "WORKFLOW_TRANSITION",
    previous_state: "INVESTIGATING",
    new_state: "WAITING_FOR_PROVIDER",
    confidence: 1.0,
    details: { assigned_provider: "Dr. Sarah Wilson", sla_window: "24h" }
  },
  {
    id: "aud-04",
    timestamp: hoursAgo(3.2),
    case_id: "RX-10484",
    actor_type: "AI",
    actor_id: "rxresolve-ai",
    actor_name: "RxResolve AI",
    actor_role: "SYSTEM",
    action: "PRIOR_AUTH_DETECTED",
    event_type: "AI_INFERENCE",
    previous_state: "NEW",
    new_state: "WAITING_FOR_INSURANCE",
    confidence: 0.91,
    details: { payer: "BCBS_IL_60054", requirement: "Electronic Prior Authorization (ePA)" }
  },
  {
    id: "aud-05",
    timestamp: hoursAgo(2.8),
    case_id: "RX-10487",
    actor_type: "HUMAN",
    actor_id: "usr-prov-01",
    actor_name: "Dr. Sarah Wilson, MD",
    actor_role: "PROVIDER",
    action: "AUTHORIZE_RENEWAL",
    event_type: "WORKFLOW_TRANSITION",
    previous_state: "WAITING_FOR_PROVIDER",
    new_state: "ACTION_REQUIRED",
    confidence: 1.0,
    details: { decision: "APPROVE", refills_approved: 3, days_supply: 90 }
  },
  {
    id: "aud-06",
    timestamp: hoursAgo(2.1),
    case_id: "RX-10485",
    actor_type: "HUMAN",
    actor_id: "usr-pract-01",
    actor_name: "Maya Lin, BSN",
    actor_role: "PRACTICE_STAFF",
    action: "CLARIFICATION_SENT",
    event_type: "WORKFLOW_TRANSITION",
    previous_state: "INVESTIGATING",
    new_state: "WAITING_FOR_PHARMACY",
    confidence: 1.0,
    details: { target_pharmacy: "Downtown Pharmacy", question: "Packaging and day supply confirmation" }
  },
  {
    id: "aud-07",
    timestamp: hoursAgo(1.5),
    case_id: "RX-10490",
    actor_type: "SYSTEM",
    actor_id: "sla-monitor",
    actor_name: "RxResolve SLA Monitor",
    actor_role: "SYSTEM",
    action: "SLA_BREACH_WARNING",
    event_type: "WORKFLOW_TRANSITION",
    previous_state: "WAITING_FOR_PROVIDER",
    new_state: "ESCALATED",
    confidence: 1.0,
    details: { hours_remaining: 1.0, escalation_reason: "Controlled substance protocol requires clinic encounter" }
  },
  {
    id: "aud-08",
    timestamp: hoursAgo(0.8),
    case_id: "RX-10491",
    actor_type: "SYSTEM",
    actor_id: "integration-gateway",
    actor_name: "EHR Clinical Bridge",
    actor_role: "SYSTEM",
    action: "GATEWAY_TIMEOUT_DURABLE_BUFFER",
    event_type: "INTEGRATION_RECOVERY",
    previous_state: "INVESTIGATING",
    new_state: "FAILED",
    confidence: 1.0,
    details: { gateway: "Epic FHIR R4", error: "Gateway 504 Gateway Timeout - Preserved in isolation queue" }
  },
  {
    id: "aud-09",
    timestamp: hoursAgo(0.4),
    case_id: "RX-10488",
    actor_type: "HUMAN",
    actor_id: "usr-pharm-01",
    actor_name: "Elena Rostova, CPhT",
    actor_role: "PHARMACY_STAFF",
    action: "DISPENSE_CONFIRMED",
    event_type: "WORKFLOW_TRANSITION",
    previous_state: "ACTION_REQUIRED",
    new_state: "RESOLVED",
    confidence: 1.0,
    details: { rx_number: "RX-8849102", status: "Dispensed and ready for patient pickup" }
  }
];

export const DEMO_INTEGRATIONS: IntegrationServiceItem[] = [
  {
    id: "int-ehr",
    name: "EHR Clinical Bridge (Epic / Cerner FHIR)",
    category: "EHR",
    protocol: "FHIR R4 / US Core STU3",
    status: "HEALTHY",
    latency_ms: 38,
    success_rate: 99.8,
    last_sync: hoursAgo(0.1),
    simulate_failure: false,
    details: { endpoint: "https://fhir.epic.sandbox.net/r4", auth: "OAuth2 Smart-on-FHIR", cached_patients: 4820 }
  },
  {
    id: "int-pharmacy",
    name: "National Pharmacy Network (Surescripts)",
    category: "Pharmacy Network",
    protocol: "NCPDP SCRIPT Standard 2017071",
    status: "HEALTHY",
    latency_ms: 74,
    success_rate: 99.2,
    last_sync: hoursAgo(0.2),
    simulate_failure: false,
    details: { endpoint: "https://directory.surescripts.net/ncpdp", transaction_type: "RxChange / RefReq", active_pharmacies: 184 }
  },
  {
    id: "int-insurance",
    name: "PBM Real-Time Benefit & Prior Auth",
    category: "Insurance/PBM",
    protocol: "X12 278 / ePA NCPDP",
    status: "DEGRADED",
    latency_ms: 1420,
    success_rate: 84.6,
    last_sync: hoursAgo(0.5),
    last_error: "PBM gateway timeout on transaction 278-PA-9921",
    simulate_failure: true,
    details: { endpoint: "https://gateway.covermymeds.com/v1", payer_id: "BCBS_IL_60054" }
  },
  {
    id: "int-ai",
    name: "RxResolve Clinical NLP Engine",
    category: "AI Engine",
    protocol: "Gemini 2.5 Flash / Local Clinical Model",
    status: "HEALTHY",
    latency_ms: 110,
    success_rate: 99.9,
    last_sync: hoursAgo(0.1),
    simulate_failure: false,
    details: { model: "Hybrid (Clinical NLP + Gemini RAG)" }
  }
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-01",
    recipient_role: "PROVIDER",
    case_id: "RX-10482",
    title: "Provider Review Required: Alex Johnson",
    message: "Demo Medication 10mg refill request awaiting clinical authorization. 18 hours remaining.",
    priority: "HIGH",
    read: false,
    action_url: "/cases/RX-10482",
    timestamp: hoursAgo(0.7)
  },
  {
    id: "notif-02",
    recipient_role: "PRACTICE_STAFF",
    case_id: "RX-10490",
    title: "SLA Approaching: Vyvanse Renewal",
    message: "Case RX-10490 has only 1.0 hour remaining on operational SLA.",
    priority: "CRITICAL",
    read: false,
    action_url: "/cases/RX-10490",
    timestamp: hoursAgo(0.3)
  }
];

export const DEMO_KNOWLEDGE_DOCUMENTS: KnowledgeDoc[] = [
  {
    id: "kb-sop-001",
    source_name: "Practice Refill SOP §4.2",
    title: "Provider Authorization & Refill Sign-Off Policy",
    category: "Practice SOPs",
    content: "When an existing prescription has zero (0) refills remaining, standard protocol dictates that an explicit provider authorization is required. Practice staff may not re-authorize refills independently without provider review if the last documented clinical encounter exceeded 6 months or if dosage adjustments occurred. Routine maintenance medications with clean visit history (<6 months) may be queued directly for Dr. review with a 24-hour target turnaround.",
    keywords: ["0 Refills", "Zero Refills", "Provider Review", "Authorization", "Sign-Off", "Prescription Expired"]
  },
  {
    id: "kb-sop-002",
    source_name: "Clinical Intake SOP §2.1",
    title: "Missing Information & Pharmacy Clarification SOP",
    category: "Practice SOPs",
    content: "A refill request missing key dispensing parameters (such as NDC, quantity dispensed, explicit day supply, or patient address verification) must be transitioned to WAITING_FOR_INFORMATION. Practice staff must initiate a structured inquiry to the requesting pharmacy. Cases in WAITING_FOR_PHARMACY for >48 hours without response shall be escalated to the supervising triage coordinator.",
    keywords: ["Missing Information", "Pharmacy Clarification", "Quantity", "Dosage", "NDC", "Unverified"]
  },
  {
    id: "kb-admin-001",
    source_name: "Administrative & PBM Guidelines v3",
    title: "Prior Authorization & Formulary Exception Routing",
    category: "Administrative Rules",
    content: "Refill requests rejected for 'PA Required' or formulary tier restrictions must undergo electronic Prior Authorization (ePA). The clinical coordinator must verify chart notes documenting previous step-therapy failure or diagnosis ICD-10 justification before routing the CoverMyMeds/Surescripts ePA request to the payer.",
    keywords: ["Prior Authorization", "PBM", "Formulary", "CoverMyMeds", "Denial", "Step Therapy"]
  },
  {
    id: "kb-admin-002",
    source_name: "Compliance & Medical Board Standard §8",
    title: "Annual Patient Encounter & Monitoring Requirement",
    category: "Administrative Rules",
    content: "For chronic maintenance medications (e.g. anti-hypertensives, statins, diabetes management), an in-person or synchronous telehealth visit within the past 12 months is legally required to authorize renewals. If the patient has not had a visit in >12 months, the provider should select 'Require Visit' and offer a bridging 30-day supply where medically appropriate.",
    keywords: ["Annual Visit", "Hypertension", "Diabetes", "Bridge Supply", "Appointment", "Follow-up"]
  },
  {
    id: "kb-workflow-001",
    source_name: "Internal Workflow Rules §1.4",
    title: "Refill Operational SLA & Escalation Rules",
    category: "Internal Workflow Rules",
    content: "Standard operational target resolution time for outpatient refills is 24 hours. Critical priority cases (life-sustaining or high-risk medications) have an SLA of 4 hours. High priority cases have an SLA of 12 hours. Any case pending in WAITING_FOR_PROVIDER for more than 18 hours is automatically designated AT RISK and escalated to the practice manager.",
    keywords: ["SLA", "Escalation", "Hours", "Timeline", "Priority", "At Risk", "Urgent"]
  },
  {
    id: "kb-workflow-002",
    source_name: "Operations Quality & Audit SOP §5",
    title: "Inter-Organizational Communication & Audit Trail",
    category: "Internal Workflow Rules",
    content: "All communications between Pharmacy Staff and Physician Practice Staff must be documented directly in the case ledger. AI-drafted messages require human verification before transmission. System integration failures (EHR FHIR or Surescripts timeout) must trigger automatic retry with exponential backoff and flag the case as degraded without data loss.",
    keywords: ["Communication", "Audit", "Integration", "Timeout", "EHR", "Failure", "Retry"]
  }
];

export const DEMO_CASE_COMMUNICATIONS: Record<string, any[]> = {
  'RX-10482': [
    {
      id: 'comm-10482-1',
      case_id: 'RX-10482',
      sender_id: 'usr-pharm-01',
      sender_name: 'Elena Rostova, CPhT',
      sender_role: 'PHARMACY_STAFF',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Refill intake received from Downtown Pharmacy for Alex Johnson (Demo Medication 10mg). 0 refills remain on original Rx. Patient has 2 doses left at home.',
      timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
      is_ai_drafted: false
    },
    {
      id: 'comm-10482-2',
      case_id: 'RX-10482',
      sender_id: 'usr-pract-01',
      sender_name: 'Maya Lin, BSN',
      sender_role: 'PRACTICE_STAFF',
      recipient_role: 'PROVIDER',
      content: 'Chart review completed. Alex has maintained 98% therapy adherence over the past 12 months with no adverse reactions noted. Routing to Dr. Sarah Wilson for renewal authorization.',
      timestamp: new Date(Date.now() - 2.5 * 3600000).toISOString(),
      is_ai_drafted: false
    },
    {
      id: 'comm-10482-3',
      case_id: 'RX-10482',
      sender_id: 'usr-prov-01',
      sender_name: 'Dr. Sarah Wilson, MD',
      sender_role: 'PROVIDER',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Encounter history verified. Annual lab panel completed 4 months ago was within normal limits. Case is approved for 3 refills (90-day supply).',
      timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
      is_ai_drafted: true
    }
  ],
  'RX-10483': [
    {
      id: 'comm-10483-1',
      case_id: 'RX-10483',
      sender_id: 'usr-pharm-01',
      sender_name: 'Elena Rostova, CPhT',
      sender_role: 'PHARMACY_STAFF',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Refill request submitted for Marcus Thorne (Atorvastatin 40mg). Original prescription has exhausted all refills. Patient reports 3 days supply remaining.',
      timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
      is_ai_drafted: false
    },
    {
      id: 'comm-10483-2',
      case_id: 'RX-10483',
      sender_id: 'usr-pract-01',
      sender_name: 'Maya Lin, BSN',
      sender_role: 'PRACTICE_STAFF',
      recipient_role: 'PROVIDER',
      content: 'Lipid panel from last visit shows LDL reduction on target. Patient requested 90-day maintenance supply. Routed to Dr. Wilson for electronic renewal sign-off.',
      timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
      is_ai_drafted: false
    }
  ],
  'RX-10484': [
    {
      id: 'comm-10484-1',
      case_id: 'RX-10484',
      sender_id: 'usr-pharm-01',
      sender_name: 'Elena Rostova, CPhT',
      sender_role: 'PHARMACY_STAFF',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Refill request for Eleanor Vance (Ozempic 1mg/dose Pen). PBM electronic claim rejected: Prior Authorization required under 2026 formulary guidelines.',
      timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
      is_ai_drafted: false
    },
    {
      id: 'comm-10484-2',
      case_id: 'RX-10484',
      sender_id: 'usr-pract-01',
      sender_name: 'Maya Lin, BSN',
      sender_role: 'PRACTICE_STAFF',
      recipient_role: 'PHARMACY_STAFF',
      content: 'ePA criteria submitted through CoverMyMeds bridge. Clinical diagnosis codes for Type 2 Diabetes (E11.9) with HbA1c 7.8% attached. Payer SLA is 24 hours.',
      timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
      is_ai_drafted: false
    }
  ],
  'RX-10485': [
    {
      id: 'comm-10485-1',
      case_id: 'RX-10485',
      sender_id: 'usr-pharm-01',
      sender_name: 'Elena Rostova, CPhT',
      sender_role: 'PHARMACY_STAFF',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Refill request for Carlos Mendez (Amoxicillin 875mg). Quantity discrepancy flagged: Original Rx was for 10-day acute course. Please clarify if second course is intended.',
      timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
      is_ai_drafted: false
    },
    {
      id: 'comm-10485-2',
      case_id: 'RX-10485',
      sender_id: 'usr-pract-01',
      sender_name: 'Maya Lin, BSN',
      sender_role: 'PRACTICE_STAFF',
      recipient_role: 'PHARMACY_STAFF',
      content: 'Contacting patient regarding persistent symptoms. If symptoms unresolved, provider requested clinic visit rather than repeated antibiotic course.',
      timestamp: new Date(Date.now() - 1 * 3600000).toISOString(),
      is_ai_drafted: false
    }
  ],
  'RX-10487': [
    {
      id: 'comm-10487-1',
      case_id: 'RX-10487',
      sender_id: 'usr-pharm-01',
      sender_name: 'Elena Rostova, CPhT',
      sender_role: 'PHARMACY_STAFF',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Downtown Pharmacy refill inquiry for David Kim (Sertraline 50mg). Patient has 2 doses left. Requesting physician sign-off.',
      timestamp: new Date(Date.now() - 8 * 3600000).toISOString(),
      is_ai_drafted: false
    },
    {
      id: 'comm-10487-2',
      case_id: 'RX-10487',
      sender_id: 'usr-prov-01',
      sender_name: 'Dr. Sarah Wilson, MD',
      sender_role: 'PROVIDER',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Refill approved. Dispatched 90-day electronic script via Surescripts. Next routine behavioral health follow-up in 6 months.',
      timestamp: new Date(Date.now() - 1.5 * 3600000).toISOString(),
      is_ai_drafted: true
    }
  ],
  'RX-10490': [
    {
      id: 'comm-10490-1',
      case_id: 'RX-10490',
      sender_id: 'usr-pharm-01',
      sender_name: 'Elena Rostova, CPhT',
      sender_role: 'PHARMACY_STAFF',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Refill request for Sophia Al-Mansoor (Vyvanse 30mg). Schedule II controlled substance protocol: Prescription cannot be refilled automatically without encounter.',
      timestamp: new Date(Date.now() - 12 * 3600000).toISOString(),
      is_ai_drafted: false
    },
    {
      id: 'comm-10490-2',
      case_id: 'RX-10490',
      sender_id: 'usr-pract-01',
      sender_name: 'Maya Lin, BSN',
      sender_role: 'PRACTICE_STAFF',
      recipient_role: 'PROVIDER',
      content: 'Escalated to clinical supervisor Marcus Vance. Patient last seen 7 months ago; state PDMP check completed. Recommending telehealth encounter.',
      timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
      is_ai_drafted: false
    }
  ],
  'RX-10491': [
    {
      id: 'comm-10491-1',
      case_id: 'RX-10491',
      sender_id: 'usr-pharm-01',
      sender_name: 'Elena Rostova, CPhT',
      sender_role: 'PHARMACY_STAFF',
      recipient_role: 'PRACTICE_STAFF',
      content: 'Electronic transmission failed for Liam O Connor (Amlodipine 5mg). EHR FHIR gateway returned connection reset during medication order dispatch.',
      timestamp: new Date(Date.now() - 14 * 3600000).toISOString(),
      is_ai_drafted: false
    },
    {
      id: 'comm-10491-2',
      case_id: 'RX-10491',
      sender_id: 'usr-admin-01',
      sender_name: 'Marcus Vance',
      sender_role: 'ADMIN',
      recipient_role: 'PHARMACY_STAFF',
      content: 'Integration health alert acknowledged. Retried through redundant NCPDP gateway. Script safely queued for transmission once EHR heartbeat recovers.',
      timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
      is_ai_drafted: false
    }
  ]
};

