import { RefillCase, User, AuditLogItem, IntegrationServiceItem, NotificationItem, KnowledgeDoc } from '../types';

export const DEMO_USERS: User[] = [
  {
    id: "usr-pharm-01",
    email: "pharmacy@rxresolve.demo",
    name: "Elena Rostova, CPhT",
    role: "PHARMACY_STAFF",
    role_title: "Lead Pharmacy Technician",
    organization_id: "org-pharm-01",
    organization_name: "Downtown Pharmacy",
    organization_type: "PHARMACY",
    avatar: "https://images.unsplash.com/photo-1594824813583-30f14652c206?w=150"
  },
  {
    id: "usr-pract-01",
    email: "practice@rxresolve.demo",
    name: "Maya Lin, BSN",
    role: "PRACTICE_STAFF",
    role_title: "Practice Care Coordinator",
    organization_id: "org-pract-01",
    organization_name: "Downtown Physician Group",
    organization_type: "PRACTICE",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150"
  },
  {
    id: "usr-prov-01",
    email: "provider@rxresolve.demo",
    name: "Dr. Sarah Wilson, MD",
    role: "PROVIDER",
    role_title: "Attending Physician, Internal Medicine",
    organization_id: "org-pract-01",
    organization_name: "Downtown Physician Group",
    organization_type: "PRACTICE",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150"
  },
  {
    id: "usr-admin-01",
    email: "admin@rxresolve.demo",
    name: "Marcus Vance",
    role: "ADMIN",
    role_title: "Director of Clinical Operations",
    organization_id: "org-healthsys-01",
    organization_name: "Metropolitan Health System",
    organization_type: "HEALTH_SYSTEM",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150"
  }
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();

export const INITIAL_CASES: RefillCase[] = [
  {
    id: "RX-10482",
    patient_id: "pat-10482",
    patient_name: "Alex Johnson",
    patient_dob: "1988-04-14",
    patient_phone: "555-014-8821",
    medication_id: "med-01",
    medication_name: "Demo Medication 10mg",
    dosage: "10mg PO Daily",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    last_fill_date: "2026-07-12",
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    pharmacy_phone: "555-321-9988",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "WAITING_FOR_PROVIDER",
    previous_status: "INVESTIGATING",
    last_status_reason: "No refills remaining; provider authorization required",
    blocker: "No refills remaining",
    blocker_category: "Provider-related",
    priority: "HIGH",
    priority_score: 78,
    owner_id: "usr-prov-01",
    owner_name: "Dr. Sarah Wilson",
    owner_role: "PROVIDER",
    required_next_action: "Provider review required",
    sla_deadline: hoursFromNow(18),
    sla_hours_remaining: 18.0,
    sla_status: "HEALTHY",
    information_completeness: {
      patient_info: true,
      medication_info: true,
      pharmacy_info: true,
      prescription_details: true,
      provider_info: true,
      required_review_completed: false,
      details: {
        patient: "Alex Johnson (DOB: 1988-04-14) - Chart Active",
        medication: "Demo Medication 10mg (NDC: 43598-012-30)",
        pharmacy: "Downtown Pharmacy (NPI: 1942857102)",
        provider: "Dr. Sarah Wilson (NPI: 1092837411)"
      }
    },
    ai_analysis: {
      blocker: "Provider authorization",
      category: "Provider-related",
      confidence: 0.94,
      recommended_action: "Route to physician practice for provider review.",
      recommended_role: "PROVIDER",
      operational_priority: "High",
      reasoning: "Existing prescription has no refills remaining. Provider clinical sign-off is required under SOP §4.2.",
      summary: "Refill request received from Downtown Pharmacy. Existing prescription has no refills remaining. Provider authorization is required. Patient and pharmacy information are complete. Case is currently waiting for provider review.",
      rag_sources: [
        {
          source: "Practice Refill SOP §4.2",
          title: "Provider Authorization & Refill Sign-Off Policy",
          category: "Practice SOPs",
          snippet: "When an existing prescription has zero (0) refills remaining, standard protocol dictates that an explicit provider authorization is required. Practice staff may not re-authorize refills independently without provider review."
        }
      ],
      created_at: hoursAgo(2)
    },
    notes: "Patient Alex Johnson taking Demo Medication 10mg maintenance. Refills exhausted.",
    created_at: hoursAgo(6),
    updated_at: hoursAgo(1)
  },
  {
    id: "RX-10483",
    patient_id: "pat-10483",
    patient_name: "Marcus Thorne",
    patient_dob: "1975-11-20",
    medication_id: "med-02",
    medication_name: "Atorvastatin 40mg",
    dosage: "40mg PO QPM",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "WAITING_FOR_PROVIDER",
    blocker: "No refills remaining",
    blocker_category: "Provider-related",
    priority: "MEDIUM",
    priority_score: 55,
    required_next_action: "Provider review required",
    sla_hours_remaining: 14.5,
    sla_status: "HEALTHY",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(9),
    updated_at: hoursAgo(2)
  },
  {
    id: "RX-10484",
    patient_id: "pat-10484",
    patient_name: "Eleanor Vance",
    patient_dob: "1962-03-09",
    medication_id: "med-03",
    medication_name: "Ozempic 1mg/dose Pen",
    dosage: "1mg SQ Weekly",
    quantity: 1,
    days_supply: 28,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-02",
    pharmacy_name: "MetroCare Community Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "WAITING_FOR_INSURANCE",
    blocker: "Prior authorization required",
    blocker_category: "Insurance/administrative",
    priority: "HIGH",
    priority_score: 75,
    required_next_action: "Submit ePA criteria to payer",
    sla_hours_remaining: 6.2,
    sla_status: "WARNING",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(18),
    updated_at: hoursAgo(4)
  },
  {
    id: "RX-10485",
    patient_id: "pat-10485",
    patient_name: "Carlos Mendez",
    patient_dob: "1994-08-30",
    medication_id: "med-04",
    medication_name: "Amoxicillin 875mg",
    dosage: "875mg PO BID x 10d",
    quantity: 20,
    days_supply: 10,
    refills_requested: 1,
    refills_remaining: 1,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "WAITING_FOR_PHARMACY",
    blocker: "Quantity clarification",
    blocker_category: "Pharmacy-related",
    priority: "MEDIUM",
    priority_score: 45,
    required_next_action: "Awaiting pharmacy response on dispensed packaging",
    sla_hours_remaining: 21.0,
    sla_status: "HEALTHY",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(3),
    updated_at: hoursAgo(1)
  },
  {
    id: "RX-10487",
    patient_id: "pat-10487",
    patient_name: "David Kim",
    patient_dob: "1983-05-18",
    medication_id: "med-05",
    medication_name: "Sertraline 50mg",
    dosage: "50mg PO Daily",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "ACTION_REQUIRED",
    blocker: "Provider authorization required",
    blocker_category: "Provider-related",
    priority: "HIGH",
    priority_score: 85,
    required_next_action: "Provider approved; dispatch electronic script",
    sla_hours_remaining: 2.5,
    sla_status: "WARNING",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: true },
    created_at: hoursAgo(22),
    updated_at: hoursAgo(2)
  },
  {
    id: "RX-10490",
    patient_id: "pat-10490",
    patient_name: "Sophia Al-Mansoor",
    patient_dob: "1995-07-11",
    medication_id: "med-06",
    medication_name: "Vyvanse 30mg",
    dosage: "30mg PO QAM",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "ESCALATED",
    blocker: "Patient visit may be required",
    blocker_category: "Provider-related",
    priority: "CRITICAL",
    priority_score: 92,
    required_next_action: "Controlled substance protocol: Schedule clinic encounter",
    sla_hours_remaining: 1.0,
    sla_status: "BREACHED",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(23),
    updated_at: hoursAgo(1)
  },
  {
    id: "RX-10491",
    patient_id: "pat-10491",
    patient_name: "Liam O'Connor",
    patient_dob: "1972-04-03",
    medication_id: "med-07",
    medication_name: "Amlodipine 5mg",
    dosage: "5mg PO Daily",
    quantity: 30,
    days_supply: 30,
    refills_requested: 1,
    refills_remaining: 0,
    pharmacy_id: "org-pharm-01",
    pharmacy_name: "Downtown Pharmacy",
    practice_id: "org-pract-01",
    practice_name: "Downtown Physician Group",
    provider_id: "usr-prov-01",
    provider_name: "Dr. Sarah Wilson",
    status: "FAILED",
    blocker: "EHR unavailable",
    blocker_category: "System/integration",
    priority: "CRITICAL",
    priority_score: 95,
    required_next_action: "EHR FHIR gateway timed out; retrying safely",
    sla_hours_remaining: 0.5,
    sla_status: "BREACHED",
    information_completeness: { patient_info: true, medication_info: true, pharmacy_info: true, prescription_details: true, provider_info: true, required_review_completed: false },
    created_at: hoursAgo(24),
    updated_at: hoursAgo(1)
  }
];

export const DEMO_ANALYTICS = {
  kpis: {
    total_refills: 142,
    active_refills: 16,
    avg_resolution_hours: 4.2,
    sla_compliance_rate: 94.7,
    ai_acceptance_rate: 91.2,
    awaiting_provider: 4,
    missing_information: 2,
    at_risk: 2,
    resolved_today: 4
  },
  bottlenecks: [
    { name: "Provider-related", count: 8, percentage: 50.0 },
    { name: "Insurance/administrative", count: 3, percentage: 18.8 },
    { name: "Pharmacy-related", count: 2, percentage: 12.5 },
    { name: "Information-related", count: 2, percentage: 12.5 },
    { name: "System/integration", count: 1, percentage: 6.2 }
  ],
  volume_trend: [
    { day: "Mon", submitted: 24, resolved: 22 },
    { day: "Tue", submitted: 31, resolved: 29 },
    { day: "Wed", submitted: 28, resolved: 26 },
    { day: "Thu", submitted: 35, resolved: 32 },
    { day: "Fri", submitted: 29, resolved: 28 },
    { day: "Sat", submitted: 12, resolved: 11 },
    { day: "Sun", submitted: 8, resolved: 8 }
  ],
  commercial_roi: {
    disclaimer: "DEMO / SIMULATED BENCHMARKS",
    annual_hours_saved: 2450,
    cost_avoidance_annual: 85750,
    therapy_abandonment_reduction_pct: 34.2
  }
};

export const DEMO_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "aud-01",
    timestamp: hoursAgo(6),
    case_id: "RX-10482",
    actor_type: "HUMAN",
    actor_id: "usr-pharm-01",
    actor_name: "Elena Rostova, CPhT",
    actor_role: "PHARMACY_STAFF",
    action: "CREATE_REFILL_CASE",
    event_type: "CASE_CREATION",
    previous_state: null as any,
    new_state: "NEW",
    confidence: 1.0,
    details: { source: "Surescripts Portal", patient: "Alex Johnson" }
  },
  {
    id: "aud-02",
    timestamp: hoursAgo(5),
    case_id: "RX-10482",
    actor_type: "AI",
    actor_id: "rxresolve-ai",
    actor_name: "RxResolve AI",
    actor_role: "SYSTEM",
    action: "BLOCKER_CLASSIFIED",
    event_type: "AI_INFERENCE",
    previous_state: "NEW",
    new_state: "TRIAGING",
    confidence: 0.94,
    details: { primary_blocker: "No refills remaining", category: "Provider-related" }
  },
  {
    id: "aud-03",
    timestamp: hoursAgo(4),
    case_id: "RX-10482",
    actor_type: "HUMAN",
    actor_id: "usr-pract-01",
    actor_name: "Maya Lin, BSN",
    actor_role: "PRACTICE_STAFF",
    action: "ROUTE_TO_PROVIDER",
    event_type: "WORKFLOW_TRANSITION",
    previous_state: "INVESTIGATING",
    new_state: "WAITING_FOR_PROVIDER",
    confidence: 1.0,
    details: { assigned_provider: "Dr. Sarah Wilson", sla_window: "24h" }
  }
];

export const DEMO_INTEGRATIONS: IntegrationServiceItem[] = [
  {
    id: "int-ehr",
    name: "EHR Clinical Bridge (Epic / Cerner FHIR)",
    category: "EHR",
    protocol: "FHIR R4 / US Core STU3",
    status: "HEALTHY",
    latency_ms: 38,
    success_rate: 99.8,
    last_sync: hoursAgo(0.1),
    simulate_failure: false,
    details: { endpoint: "https://fhir.epic.sandbox.net/r4", auth: "OAuth2 Smart-on-FHIR", cached_patients: 4820 }
  },
  {
    id: "int-pharmacy",
    name: "National Pharmacy Network (Surescripts)",
    category: "Pharmacy Network",
    protocol: "NCPDP SCRIPT Standard 2017071",
    status: "HEALTHY",
    latency_ms: 74,
    success_rate: 99.2,
    last_sync: hoursAgo(0.2),
    simulate_failure: false,
    details: { endpoint: "https://directory.surescripts.net/ncpdp", transaction_type: "RxChange / RefReq", active_pharmacies: 184 }
  },
  {
    id: "int-insurance",
    name: "PBM Real-Time Benefit & Prior Auth",
    category: "Insurance/PBM",
    protocol: "X12 278 / ePA NCPDP",
    status: "DEGRADED",
    latency_ms: 1420,
    success_rate: 84.6,
    last_sync: hoursAgo(0.5),
    last_error: "PBM gateway timeout on transaction 278-PA-9921",
    simulate_failure: true,
    details: { endpoint: "https://gateway.covermymeds.com/v1", payer_id: "BCBS_IL_60054" }
  },
  {
    id: "int-ai",
    name: "RxResolve Clinical NLP Engine",
    category: "AI Engine",
    protocol: "Gemini 2.5 Flash / Local Clinical Model",
    status: "HEALTHY",
    latency_ms: 110,
    success_rate: 99.9,
    last_sync: hoursAgo(0.1),
    simulate_failure: false,
    details: { model: "Hybrid (Clinical NLP + Gemini RAG)" }
  }
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-01",
    recipient_role: "PROVIDER",
    case_id: "RX-10482",
    title: "Provider Review Required: Alex Johnson",
    message: "Demo Medication 10mg refill request awaiting clinical authorization. 18 hours remaining.",
    priority: "HIGH",
    read: false,
    action_url: "/cases/RX-10482",
    timestamp: hoursAgo(0.7)
  },
  {
    id: "notif-02",
    recipient_role: "PRACTICE_STAFF",
    case_id: "RX-10490",
    title: "SLA Approaching: Vyvanse Renewal",
    message: "Case RX-10490 has only 1.0 hour remaining on operational SLA.",
    priority: "CRITICAL",
    read: false,
    action_url: "/cases/RX-10490",
    timestamp: hoursAgo(0.3)
  }
];

export const DEMO_KNOWLEDGE_DOCUMENTS: KnowledgeDoc[] = [
  {
    id: "sop-01",
    source_name: "Practice SOP §4.2",
    title: "Zero Refills Remaining Renewal Protocol",
    category: "Practice SOPs",
    content: "When an existing prescription has zero (0) refills remaining, standard protocol dictates that an explicit provider authorization is required. Routine maintenance medications with clean visit history (<6 months) may be queued directly for Dr. review with a 24-hour target turnaround.",
    keywords: ["0 Refills", "Maintenance Rx", "Provider Review", "24h SLA"]
  },
  {
    id: "sop-02",
    source_name: "Practice SOP §6.1",
    title: "Annual Encounter & Clinical Monitoring Policy",
    category: "Practice SOPs",
    content: "For chronic maintenance medications (e.g. anti-hypertensives, statins, diabetes management), an in-person or synchronous telehealth visit within the past 12 months is required to authorize renewals.",
    keywords: ["Annual Visit", "Hypertension", "Diabetes", "Bridge Supply"]
  },
  {
    id: "sop-03",
    source_name: "Admin Rule §8.0",
    title: "Prior Authorization & Formulary Exception Routing",
    category: "Administrative Rules",
    content: "If a refill request triggers a PBM formulary reject or prior authorization requirement, the case must be categorized as Insurance/Administrative and assigned to Practice Staff within 4 hours.",
    keywords: ["Prior Authorization", "PBM", "Formulary", "CoverMyMeds"]
  }
];
